{% set name = "docx2pdf" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docx2pdf-{{ version }}.tar.gz
  sha256: 6d2c20f9ad36eec75f4da017dc7a97622946954a6124ca0b11772875fa86fbed

build:
  number: 3
  skip: true  # [py>=40 or linux]
  entry_points:
    - docx2pdf = docx2pdf:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - appscript >=1.1.0,<2.0.0  # [osx]
    - importlib_metadata >=1.3.0,<2.0.0  # [py<38]
    - python
    - pywin32 >=227,<228  # [win]
    - tqdm >=4.41.0,<5.0.0

test:
  imports:
    - docx2pdf
  commands:
    - pip check
    - docx2pdf --help
  requires:
    - pip

about:
  home: https://github.com/AlJohri/docx2pdf
  summary: Convert docx to pdf on Windows or macOS directly using Microsoft Word (must be installed).
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jaimeambrus
